### PR TITLE
puppetdb/api.py|types.py: Marking noop runs with no pending changes as type 'unchanged'

### LINKED ISSUE #103: noop puppet runs with no changes reporting as 'noop' instead of 'unchanged' for puppetdb > 4.1.0
Scenario: puppet is running as --noop every 30 minutes, and so far they were being reported in puppetboard as 'unchanged'; which is exactly what I expected, as no 'noops' events existed. It was pypuppetdb 0.3.1, puppetdb 4.0.x. 

Something example code to reproduce it:
```
from pypuppetdb import connect

puppetdb = connect(host='puppetdb', port=8080, timeout=20,)
nodes = puppetdb.nodes(with_status=True)
for node in nodes:
  print(node.name + ' - ' + puppet.status)
```

Looking at https://github.com/voxpupuli/pypuppetdb/blob/master/pypuppetdb/api.py#L413, it appears that I was getting in the 'else' clause, because 'latest_report_noop' was only included in puppetdb [4.1.0](https://docs.puppet.com/puppetdb/latest/release_notes.html#section-6):

```
                    if node['latest_report_noop']:
                        node['status'] = 'noop'
                    else:
                        node['status'] = node['latest_report_status']
```

I upgraded puppetdb from 4.0.x to 4.2.x. And suddenly now those same nodes are reporting as 'noop' regardless if there are changes or not to be applied. I suppose you wouldn't expect such change of behaviour, and in all fairness, puppetboard does treat 'noop' as 'pending changes'. 

Shouldn't it be using `latest_report_noop_pending` instead of `latest_report_noop`?

In case it helps, an example output in puppetdb 4.2.x, after noop without changes. 
```
  {
    "deactivated": null,
    "latest_report_hash": "02f848510cab4b519a58d3698ef9b07459914f44",
    "facts_environment": "production",
    "cached_catalog_status": "not_used",
    "report_environment": "production",
    "latest_report_corrective_change": null,
    "catalog_environment": "production",
    "facts_timestamp": "2016-08-30T13:18:28.466Z",
    "latest_report_noop": true,
    "expired": null,
    "latest_report_noop_pending": false,
    "report_timestamp": "2016-08-30T13:18:27.019Z",
    "certname": "9745e1389f91",
    "catalog_timestamp": "2016-08-30T13:18:28.856Z",
    "latest_report_status": "unchanged"
  }
```

### PR DESCRIPTION
**Pull request by cintiadr**
Resolves #103

### CODE REVIEW

**Comment by corey-hammerton** [comment]
Can you apply the same logic to the Node object? It has the latest_report_noop_pending flag too.

**Comment by cintiadr** [comment]
I think it made sense to move to Node object, it's even nicely testable now :)

Anyway, as I mentioned I really have no way to test this code in puppetdb 3.x, or even 4.0.x and 4.1.x. 

Looking at the code, tests and documentation, I ~believe~ this should work, but it's hard to say without actually testing it. 

Do you have any docker container/vagrant box available for such tests?

**Comment by cintiadr** [comment]
Anything else that needs to be done?

**Comment by corey-hammerton** [comment]
Doesn't look like it. Sorry I haven't had a chance recently to work on the project. I'll merge this when I can.

**Pull request merged**
