### PR TITLE
QueryBuilder: Added support for FromOperator, arrays and FromOperator with InOperator

### PR DESCRIPTION
**Pull request by dwoldenberg1**
Same as earlier pull request, but tested against Travis CI (and passing locally). Also added a check that array depth is maximum one.

### CODE REVIEW

**Comment by dwoldenberg1** [comment]
The Python 3.4 build errors out but that seems to be out of my control.

**Comment by mterzo** [comment]
Was a strange build fluke.  Checked the mainline build log 28 days ago was 3.4.6 and we are pined to a specific six version, so shouldn't have had a problem.

**Comment by mterzo** [comment]
Can you update the docs in section: https://github.com/voxpupuli/pypuppetdb#query-builder

thanks.

**Comment by dwoldenberg1** [comment]
I am planning on adding support for a few other features of the web API so I thought I would wait and do all the documentation at the same time. I just wanted to see what your pull request process was like (I have not made many before).

**Comment by dwoldenberg1** [comment]
Added brief documentation

**Comment by dwoldenberg1** [comment]
Is there anything I have do for this PR? Am I forgetting something?

**Comment by dwoldenberg1** [comment]
Added the FromOperator and support for it in the InOperator. Added corresponding pytests. Also added examples to the documentation. Anything else needed from me?

**Comment by bastelfreak** [comment]
hey @mterzo, can you please review this?

**Pull request merged**
