### PR TITLE
Added support for RBAC token authentication

### PR DESCRIPTION
**Pull request by exodusftw**
docs/quickstart.rst - added documentation regarding RBAC token
authentication and how this is configured via connect()

pypuppetdb/**init**.py - added additional documentation for rbac token
authenticationa and defined token arg for passing to connect()

pypuppetdb/api.py - added support for RBAC token authentication and
ensured that session headers would contain the X-Authentication object
if a token is passed. Additionally, passing a token will force the
https protocol.

tests/test_baseapi.py - added tests for validating token argument
as well as session header tests and validation of protocols when
a token is passed

### CODE REVIEW

**Comment by exodusftw** [comment]
Will have to dig into this test issue, at first glance, I'm not positive why this would generate a KeyError. I know the base code is functional against a >=4.2 version of PE puppetDB, but I don't have an adequate test environment on my local machine to accurately simulate.

**Comment by exodusftw** [comment]
anybody worked with HTTPretty enough to know why this key error would be thrown when trying to pass the X-Authentication header?

**Comment by redref** [comment]
@exodusftw 
Your headers are set only in __init__ method. Even, if you add token later, requests are made without the header.

Submitted exodusftw#1 to you fixing the tests.

**Comment by redref** [comment]
@exodusftw also (just notice), please make a descriptive commit message and rebase your branch (just to make sure everything is fine).

**Comment by mterzo** [comment]
Closed in favor for #123

**Pull request closed without merging**
